/*

 BLOCKTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __blocktiles_h_INCLUDE
#define __blocktiles_h_INCLUDE

/* Bank of tiles. */
#define blockTilesBank 0
/* Start of tile array. */
extern const unsigned char blockTiles[];

#endif

/* End of BLOCKTILES.H */
