/*

 CONGRATSSCREENMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : ..\gbr\congrats.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __congratsscreenmap_h_INCLUDE
#define __congratsscreenmap_h_INCLUDE

#define congratsMapWidth 20
#define congratsMapHeight 18
#define congratsMapBank 0

extern const unsigned char congratsMap[];

#endif

/* End of CONGRATSSCREENMAP.H */
