/*

 GAMEBACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : ..\gbr\blocksfatcheckered.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __gamebackgroundmap_h_INCLUDE
#define __gamebackgroundmap_h_INCLUDE

#include <gbdk/platform.h>

BANKREF_EXTERN(gamebackgroundmap)

#define gameBackgroundMapWidth 20
#define gameBackgroundMapHeight 18
#define gameBackgroundMapBank 0

extern const unsigned char gameBackgroundMap[];

#endif

/* End of GAMEBACKGROUNDMAP.H */
