//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_gb_border_H
#define METASPRITE_gb_border_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define gb_border_TILE_ORIGIN 0
#define gb_border_TILE_H 8
#define gb_border_WIDTH 256
#define gb_border_HEIGHT 224
#define gb_border_TILE_COUNT 61
#define gb_border_MAP_ATTRIBUTES 0
#define gb_border_TILE_PALS 0

BANKREF_EXTERN(gb_border)

extern const palette_color_t gb_border_palettes[16];
extern const uint8_t gb_border_tiles[1952];
extern const unsigned char gb_border_map[1792];

#endif