/*

 HELPSLIDE2MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : ..\gbr\blocksfatcheckered.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __helpslide2map_h_INCLUDE
#define __helpslide2map_h_INCLUDE

#define helpSlide2MapWidth 20
#define helpSlide2MapHeight 18
#define helpSlide2MapBank 0

extern const unsigned char helpSlide2Map[];

#endif

/* End of HELPSLIDE2MAP.H */
