/*

 HELPROTATEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : ..\gbr\blocksfatcheckered.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __helprotatemap_h_INCLUDE
#define __helprotatemap_h_INCLUDE

#define helpRotateMapWidth 20
#define helpRotateMapHeight 18
#define helpRotateMapBank 0

extern const unsigned char helpRotateMap[];

#endif

/* End of HELPROTATEMAP.H */
