/*

 SEGABUTTONTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 2

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __segabuttontiles_h_INCLUDE
#define __segabuttontiles_h_INCLUDE

#include <gbdk/platform.h>

BANKREF_EXTERN(segabuttontiles)

/* Bank of tiles. */
#define segaButtonTilesBank 255
/* Start of tile array. */
extern const unsigned char segaButtonTiles[];

#endif

/* End of SEGABUTTONTILES.H */
