/*

 SELECTORTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 40

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/
#ifndef __selectortiles_h_INCLUDE
#define __selectortiles_h_INCLUDE

#include <gbdk/platform.h>

BANKREF_EXTERN(selectortiles)

/* Bank of tiles. */
#define selectorTilesBank 0
/* Start of tile array. */
extern const unsigned char selectorTiles[];

#endif

/* End of SELECTORTILES.H */
