/*

 TITLESCREENMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : ..\gbr\titletilesfat.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __titlescreenmap_h_INCLUDE
#define __titlescreenmap_h_INCLUDE

#define titlescreenMapWidth 20
#define titlescreenMapHeight 18
#define titlescreenMapBank 0

extern const unsigned char titlescreenMap[];

#endif

/* End of TITLESCREENMAP.H */
