/*

 GAMEBACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\gbdk\projects\waternet\tiles\blocksfat.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define gameBackgroundWidth 20
#define gameBackgroundHeight 18
#define gameBackgroundBank 0

extern const unsigned char gameBackground[];

/* End of GAMEBACKGROUND.H */
