/*

 HELPROTATE2MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\github\waternet_gamboy\source\tiles\gbr\blocksfatcheckered.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define helpRotate2MapWidth 20
#define helpRotate2MapHeight 18
#define helpRotate2MapBank 0

extern unsigned char helpRotate2Map[];

/* End of HELPROTATE2MAP.H */
