/*

 HELPROTATESLIDEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\github\waternet_gamboy\source\tiles\gbr\blocksfatcheckered.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __helprotateslidemap_h_INCLUDE
#define __helprotateslidemap_h_INCLUDE

#define helpRotateSlideMapWidth 20
#define helpRotateSlideMapHeight 18
#define helpRotateSlideMapBank 0

extern const unsigned char helpRotateSlideMap[];

#endif

/* End of HELPROTATESLIDEMAP.H */
