/*

 HELPROTATEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\github\waternet_gamboy\source\tiles\gbr\blocksfatcheckered.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define helpRotateMapWidth 20
#define helpRotateMapHeight 18
#define helpRotateMapBank 0

extern unsigned char helpRotateMap[];

/* End of HELPROTATEMAP.H */
