/*

 HELPROTATESLIDE2MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\github\waternet_gamboy\source\tiles\gbr\blocksfatcheckered.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __helprotateslide2map_h_INCLUDE
#define __helprotateslide2map_h_INCLUDE

#define helpRotateSlide2MapWidth 20
#define helpRotateSlide2MapHeight 18
#define helpRotateSlide2MapBank 0

extern const unsigned char helpRotateSlide2Map[];

#endif

/* End of HELPROTATESLIDE2MAP.H */
