
# Platform specific flags for compiling (only populate if they're both present)
ifneq ($(strip $(PORT)),)
ifneq ($(strip $(PLAT)),)
CFLAGS += -m$(PORT):$(PLAT)
endif
endif

ifeq ($(strip $(RELEASE)),1)
CFLAGS += $(CFLAGS_RELEASE)
endif

# Called by the individual targets below to build a ROM
build-target: $(BINS)

clean-target:
	rm -rf $(OBJDIR)
	rm -rf $(BINDIR)
	
# - GAMEBOY -
gb-clean:
	${MAKE} clean-target EXT=gb
gb:
	${MAKE} build-target PORT=gbz80 PLAT=gb EXT=gb
gb-release:
	${MAKE} build-target PORT=gbz80 PLAT=gb EXT=gb RELEASE=1

# - GAMEBOY COLOR -
gbc-clean:
	${MAKE} clean-target EXT=gbc
gbc:
	${MAKE} build-target PORT=gbz80 PLAT=gb EXT=gbc
gbc-release:
	${MAKE} build-target PORT=gbz80 PLAT=gb EXT=gbc RELEASE=1

# - ANALOGUE POCKET -
pocket-clean:
	${MAKE} clean-target EXT=pocket
pocket:
	${MAKE} build-target PORT=gbz80 PLAT=ap EXT=pocket
pocket-release:
	${MAKE} build-target PORT=gbz80 PLAT=ap EXT=pocket RELEASE=1

# - MEGADUCK / COUGAR BOY -
megaduck-clean:
	${MAKE} clean-target EXT=duck
megaduck:
	${MAKE} build-target PORT=gbz80 PLAT=duck EXT=duck
megaduck-release:
	${MAKE} build-target PORT=gbz80 PLAT=duck EXT=duck RELEASE=1

# - MASTER SYSTEM -
sms-clean:
	${MAKE} clean-target EXT=sms
sms:
	${MAKE} build-target PORT=z80 PLAT=sms EXT=sms
sms-release:
	${MAKE} build-target PORT=z80 PLAT=sms EXT=sms RELEASE=1

# - GAME GEAR -
gg-clean:
	${MAKE} clean-target EXT=gg
gg:
	${MAKE} build-target PORT=z80 PLAT=gg EXT=gg
gg-release:
	${MAKE} build-target PORT=z80 PLAT=gg EXT=gg RELEASE=1

# - BATTERYLESS GAMEBOY COLOR -

# Generic Flash Cartridge (WR/555/A9)
gbc-batteryless-DMG_Generic_WR_555_A9-clean:
	${MAKE} clean-target EXT=batteryless-DMG_Generic_WR_555_A9.gbc CARTTYPEDIR=DMG_Generic_WR_555_A9
gbc-batteryless-DMG_Generic_WR_555_A9:
	${MAKE} build-target PORT=gbz80 PLAT=gb EXT=batteryless-DMG_Generic_WR_555_A9.gbc CARTTYPEDIR=DMG_Generic_WR_555_A9
gbc-batteryless-DMG_Generic_WR_555_A9-release:
	${MAKE} build-target PORT=gbz80 PLAT=gb EXT=batteryless-DMG_Generic_WR_555_A9.gbc CARTTYPEDIR=DMG_Generic_WR_555_A9 RELEASE=1

#DMG_AM29LV160MB for the following cartridges:
# "SD007_BV5_V3 with AM29LV160MB",
# "SD007_TSOP_48BALL with L160DB12VI",
# "SD007_TSOP_48BALL with AM29LV160DB",
# "2006_TSOP_64BALL_QFP48 with AL016J55FFAR2",
# "SD007_TSOP_64BALL_SOP28 with unlabeled flash chip",
# "SD007_TSOP_29LV017D with L017D70VC",
# "SD007_TSOP_48BALL with AM29LV160DT"

gbc-batteryless-DMG_AM29LV160MB-clean:
	${MAKE} clean-target EXT=batteryless-DMG_AM29LV160MB.gbc CARTTYPEDIR=DMG_AM29LV160MB
gbc-batteryless-DMG_AM29LV160MB:
	${MAKE} build-target PORT=gbz80 PLAT=gb EXT=batteryless-DMG_AM29LV160MB.gbc CARTTYPEDIR=DMG_AM29LV160MB
gbc-batteryless-DMG_AM29LV160MB-release:
	${MAKE} build-target PORT=gbz80 PLAT=gb EXT=batteryless-DMG_AM29LV160MB.gbc CARTTYPEDIR=DMG_AM29LV160MB RELEASE=1