
# Platform specific flags for compiling (only populate if they're both present)
ifneq ($(strip $(PORT)),)
ifneq ($(strip $(PLAT)),)
CFLAGS += -m$(PORT):$(PLAT)
endif
endif

ifeq ($(strip $(RELEASE)),1)
CFLAGS += $(CFLAGS_RELEASE)
endif

# Called by the individual targets below to build a ROM
build-target: $(BINS)

clean-target:
	rm -rf $(OBJDIR)
	rm -rf $(BINDIR)
	
# - GAMEBOY -
gb-clean:
	${MAKE} clean-target EXT=gb
gb:
	${MAKE} build-target PORT=gbz80 PLAT=gb EXT=gb
gb-release:
	${MAKE} build-target PORT=gbz80 PLAT=gb EXT=gb RELEASE=1

# - GAMEBOY COLOR -
gbc-clean:
	${MAKE} clean-target EXT=gbc
gbc:
	${MAKE} build-target PORT=gbz80 PLAT=gb EXT=gbc
gbc-release:
	${MAKE} build-target PORT=gbz80 PLAT=gb EXT=gbc RELEASE=1

# - ANALOGUE POCKET -
pocket-clean:
	${MAKE} clean-target EXT=pocket
pocket:
	${MAKE} build-target PORT=gbz80 PLAT=ap EXT=pocket
pocket-release:
	${MAKE} build-target PORT=gbz80 PLAT=ap EXT=pocket RELEASE=1

# - MEGADUCK / COUGAR BOY -
megaduck-clean:
	${MAKE} clean-target EXT=duck
megaduck:
	${MAKE} build-target PORT=gbz80 PLAT=duck EXT=duck
megaduck-release:
	${MAKE} build-target PORT=gbz80 PLAT=duck EXT=duck RELEASE=1

# - MASTER SYSTEM -
sms-clean:
	${MAKE} clean-target EXT=sms
sms:
	${MAKE} build-target PORT=z80 PLAT=sms EXT=sms
sms-release:
	${MAKE} build-target PORT=z80 PLAT=sms EXT=sms RELEASE=1

# - GAME GEAR -
gg-clean:
	${MAKE} clean-target EXT=gg
gg:
	${MAKE} build-target PORT=z80 PLAT=gg EXT=gg
gg-release:
	${MAKE} build-target PORT=z80 PLAT=gg EXT=gg RELEASE=1

# - BATTERYLESS GAMEBOY -
gb-batteryless-gen_WR-555-A9-clean:
	${MAKE} clean-target EXT=batterylesssave.gen_WR-555-A9.gb CARTTYPEDIR=generic_flash_cartridge_WR-555-A9
gb-batteryless-gen_WR-555-A9:
	${MAKE} build-target PORT=gbz80 PLAT=gb EXT=batterylesssave.gen_WR-555-A9.gb CARTTYPEDIR=generic_flash_cartridge_WR-555-A9
gb-batteryless-gen_(WR-555-A9)-release:
	${MAKE} build-target PORT=gbz80 PLAT=gb EXT=batterylesssave.gen_WR-555-A9.gb CARTTYPEDIR=generic_flash_cartridge_WR-555-A9 RELEASE=1

# - BATTERYLESS GAMEBOY COLOR -
gbc-batteryless-gen_WR-555-A9-clean:
	${MAKE} clean-target EXT=batterylesssave.gen_WR-555-A9.gbc CARTTYPEDIR=generic_flash_cartridge_WR-555-A9
gbc-batteryless-gen_WR-555-A9:
	${MAKE} build-target PORT=gbz80 PLAT=gb EXT=batterylesssave.gen_WR-555-A9.gbc CARTTYPEDIR=generic_flash_cartridge_WR-555-A9
gbc-batteryless-gen_WR-555-A9-release:
	${MAKE} build-target PORT=gbz80 PLAT=gb EXT=batterylesssave.gen_WR-555-A9.gbc CARTTYPEDIR=generic_flash_cartridge_WR-555-A9 RELEASE=1