name: Waternet Build And Package

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
   branches: [ main ]
  # pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        rom:
          - gb 
          - gbc
          - gg
          - pocket
          - sms
          - megaduck
        include:
          - rom: gb
            ext: gb
            name: Nintendo Game Boy
          - rom: gbc
            ext: gbc
            name: Nintendo Game Boy Color
          - rom: gg
            ext: gg
            name: Sega Game Gear
          - rom: pocket
            ext: pocket
            name: Analogue Pocket
          - rom: sms
            ext: sms
            name: Sega Master System
          - rom: megaduck
            ext: duck
            name: Mega Duck
    runs-on: ubuntu-latest
        
    steps:
      # ==== dependencies ====
      - name: Install Make
        run: sudo apt-get install -y make

      - name: Install p7zip
        run: sudo apt-get install -y make
        
       # ==== Build Steps ====
      - name: Check out Sources
        uses: actions/checkout@v2
        with:
          submodules: false
      
      - name: Grab GBDK
        run: |
          cd gdbk_build
          tar -xvf "Linux-x64 build.tar.gz"
          cd ..
          
      - name: Build
        run: |
          export GBDK_HOME="$PWD/gdbk_build/gbdk/"
          echo $GBDK_HOME
          cd source
          make ${{ matrix.rom }}
          cd ..
          
      - name: Prepare artifacts
        run: |
          mkdir -p package
          cp "source/build/${{ matrix.ext }}/waternet.${{ matrix.ext }}" package
          cp LICENSE package
          cp "cartridge_labels/waternet.${{ matrix.rom }}.png" package
      
      - name: Make Readme.pdf
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: .
          output_dir: package
          images_dir: images
          # for example <img src="./images/file-name.png">
          image_import: images
          # Default is true, can set to false to only get PDF files
          build_html: false
               
      - name: Store build
        uses: actions/upload-artifact@v2
        with:
          name: Waternet - ${{ matrix.name }}
          path: package/
          # retention-days: 30
