# This is a basic workflow to help you get started with Actions

name: Waternet Build And Package

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #  branches: [ main ]
  # pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        rom:
          - gb 
          - gbc
          - gg
          - pocket
          - sms
          - duck
        include:
          - rom: gb
            name: Nintedo Game Boy
          - rom: gbc
            name: Nintedo Game Boy Color
          - rom: gg
            name: Sega Game Gear
          - rom: pocket
            name: Analogue Pocket
          - rom: sms
            name: Sega Master System
          - rom: duck
            name: Mega Duck
    runs-on: windows-latest
    
    steps:
      # ==== dependencies ====
      - name: Windows Depends MSYS2/MinGW64
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          path-type: minimal #strict
          release: false
          update: false
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            
      - name: Grab gbdk-2020
        run: |
          # temporary use this artifact until release gets updates
          curl -Lo gbdk.zip https://github.com/gbdk-2020/gbdk-2020/suites/4897103053/artifacts/140584335
          7z x gbdk.zip      
       
       # ==== Build Steps ====
      - name: Check out Sources
        uses: actions/checkout@v2
        with:
          path: waternet_gamboy
          submodules: false
          
      - name: Build
        shell: cmd
        run: |
          set GBDK_HOME=%CD%\gbdk
          cd waternet_gamboy
          msys2 -c 'make ${{ matrix.rom }}'
          cd ..
      
      - name: Package Build
        shell: cmd
        run: |
          cd waternet_gamboy
          mkdir package
          cd build
          7z a ../package/waternet ${{ matrix.name }}.zip waternet.${{ matrix.rom }}
          cd ..
          cd ..
          
      - name: Store build
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }} build
          path: waternet_gamboy/package/waternet ${{ matrix.name }}.zip
          # retention-days: 30
